# Primeiras impressões sobre o conjunto de dados.

In [3]:
import pandas as pd
import pyarrow
import numpy as np
from pathlib import Path

In [5]:
# Encontrando o arquivo.

raiz_do_projeto = Path.cwd().parent
caminho_db = raiz_do_projeto / "dados_otimizados" / "dados_otimizados.parquet"

### Fazendo leituras inicias
Conhecendo a base de dados...

In [22]:
df = pd.read_parquet(caminho_db)

df.head()

,Instituição,Cod.IBGE,UF,População,Coluna,Conta,Identificador da Conta,Valor,Ano,Função/Subfunção
0,Prefeitura Municipal de Rio Branco - AC,1200401,AC,407319,Despesas Empenhadas,Despesas Exceto Intraorçamentárias,siconfi-cor_TotalDespesas,8.748853e+08,2020,Total/Agregador
1,Prefeitura Municipal de Rio Branco - AC,1200401,AC,407319,Despesas Empenhadas,01 - Legislativa,siconfi-cor_TotalDespesas,2.901406e+07,2020,Função
2,Prefeitura Municipal de Rio Branco - AC,1200401,AC,407319,Despesas Empenhadas,01.031 - Ação Legislativa,siconfi-cor_TotalDespesas,2.901406e+07,2020,Subfunção
3,Prefeitura Municipal de Rio Branco - AC,1200401,AC,407319,Despesas Empenhadas,03 - Essencial à Justiça,siconfi-cor_TotalDespesas,1.882290e+07,2020,Função
4,Prefeitura Municipal de Rio Branco - AC,1200401,AC,407319,Despesas Empenhadas,03.092 - Representação Judicial e Extrajudicial,siconfi-cor_TotalDespesas,1.882290e+07,2020,Subfunção

In [23]:
df.tail(5)

,Instituição,Cod.IBGE,UF,População,Coluna,Conta,Identificador da Conta,Valor,Ano,Função/Subfunção
50329,Prefeitura Municipal do Rio de Janeiro - RJ,3304557,RJ,6625849,Inscrição de Restos a Pagar Processados,FU26 - Demais Subfunções,siconfi-cor_TotalDespesas,21091624.99,2025,Subfunção
50330,Prefeitura Municipal do Rio de Janeiro - RJ,3304557,RJ,6625849,Inscrição de Restos a Pagar Processados,27 - Desporto e Lazer,siconfi-cor_TotalDespesas,1943010.63,2025,Função
50331,Prefeitura Municipal do Rio de Janeiro - RJ,3304557,RJ,6625849,Inscrição de Restos a Pagar Processados,27.812 - Desporto Comunitário,siconfi-cor_TotalDespesas,1935090.75,2025,Subfunção
50332,Prefeitura Municipal do Rio de Janeiro - RJ,3304557,RJ,6625849,Inscrição de Restos a Pagar Processados,27.122 - Administração Geral,siconfi-cor_TotalDespesas,7919.88,2025,Subfunção
50333,Prefeitura Municipal do Rio de Janeiro - RJ,3304557,RJ,6625849,Inscrição de Restos a Pagar Processados,Despesas Intraorçamentárias,siconfi-cor_TotalDespesas,3555064.50,2025,Total/Agregador

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50334 entries, 0 to 50333
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Instituição             50334 non-null  str
 1   Cod.IBGE                50334 non-null  int64
 2   UF                      50334 non-null  str
 3   População               50334 non-null  int64
 4   Coluna                  50334 non-null  str
 5   Conta                   50334 non-null  str
 6   Identificador da Conta  50334 non-null  str
 7   Valor                   50334 non-null  float64
 8   Ano                     50334 non-null  int64
 9   Função/Subfunção        50334 non-null  str
dtypes: float64(1), int64(3), str(6)
memory usage: 10.1 MB

In [25]:
# Verificando valores nulos e duplicados

print("Número de valores nulos:\n", df.isnull().sum())
print("\nNúmero de valores duplicados:", df.duplicated().sum())

Número de valores nulos:
 Instituição               0
Cod.IBGE                  0
UF                        0
População                 0
Coluna                    0
Conta                     0
Identificador da Conta    0
Valor                     0
Ano                       0
Função/Subfunção          0
dtype: int64

Número de valores duplicados: 0

Contagem de dados em cada ano

In [26]:
contagem = df['Ano'].value_counts()

print("Contagem de valores únicos na coluna 'Ano':\n", contagem)

Contagem de valores únicos na coluna 'Ano':
 Ano
2023    9576
2024    9528
2022    9312
2020    8988
2021    8867
2025    4063
Name: count, dtype: int64

Percebe-se uma diferença a cada um dos anos, com 2025 sendo o menor. Como foi informado no README, no 2025 possua dados incompletos.